### ISSUE TITLE
[Question] Understanding Percentiles

### ISSUE THREAD

**Issue by mbauer-0805** [seize-the-dave/get-kanban-simulation#14]
Hi David,
first of all I would like to say thank you for this project!
I played around with the simulation an I'm sure that it will be a big add-on if you use the simulation for a debrief after the game.

I struggle around to understand the distribution of the percentiles.
My understanding is that a percentile of 80% means that this result is better than 80% of the results from the simulation.

Now I see the the highest outcome is always the 50% percentile and the lowest is the 95% percentile. Where is the error in my thoughts?
Thank you very much,
Greetings.
Marc Bauer

**Comment by seize-the-dave** [comment]
Hi Marc,

It might be easier to express it as follows:

- 95% of simulations will score $x or greater
- 50% of simulations will score $y or greater

Therefore the 95% score is lower (easier to achieve).

Dave

**Comment by mbauer-0805** [comment]
Thank you Dave for the explanation, 
that make sense for me. I think we can close the issue. :-)
Greeting
Marc
