### ISSUE TITLE
[Improvement] Configuration and Logging

### ISSUE THREAD

**Issue by mbauer-0805** [seize-the-dave/get-kanban-simulation#15]
Hi Dave,
I try to figure it out by myself, with out success until now.
I like to change the policies, for example the set the WIP for the "Selected" column to run the simulation with the different settings (a config file for different settings would be great) and compare the results. 
For this it would be also helpful to have a log with I'm able to plot a histogram, with gnuplot or  similar.
If you can give me a hint where to start would be great.
Thank you,
Greetings
Marc

**Comment by seize-the-dave** [comment]
There's some work on a branch here: https://github.com/seize-the-dave/get-kanban-simulation/tree/run-configurations which will make more sense.  That branch has a lot more useful work on it for configurations, but needs some work to return it to green.

**Comment by seize-the-dave** [comment]
@mbauer-0805 all unit tests are fixed and the build passes.  I will merge to master as soon as I get the green light from Travis.

**Comment by seize-the-dave** [comment]
@mbauer-0805 everything is now merged into master and builds.  The BoardRunner class controls the execution, and it ought to be possible to output a histogram of information from there.

I did a talk using this at London Lean Kanban Days if that's useful: https://www.infoq.com/presentations/getkanban-board-game/

**Comment by mbauer-0805** [comment]
Hi Dave,
thank you very much, this is basically what I would like to have to simulate and show the effects of different strategies, WIP, and so on.
What would be great, but more nice to have is:
- a config file, so that I could change the WIP settings with out the need to build a new jar file. 
- a output file, like an out.csv with different columns for the different strategies.
I know your great video, this inspired me to play around with your simulation.
Thank you again.
Greetings
Marc

**Comment by seize-the-dave** [comment]
@mbauer-0805 is this something you'd be prepared to contribute?

**Comment by mbauer-0805** [comment]
Hi Dave,
do not understand me wrong. It was just thought for future improvements that I had in my mind.
Unfortunately my developer skills are almost non existent. Otherwise I would be happy to contribute. 
Many Greetings
Marc

**Comment by seize-the-dave** [comment]
Ah, got it.  Thanks.  I think it's unlikely I'll get around to it, but I'll
keep it open as a reminder.

Dave
